services:
  client-web:
    container_name: client-web
    build:
      context: ./client-web
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
      # ENV_VARIABLE: ${ENV_VARIABLE}
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}


    # Set environment variables based on the .env file
    env_file:
      - /client-web/.env
    volumes:
      - ./client-web/src:/app/src
      - ./client-web/public:/app/public
    restart: always
    ports:
      - 3000:3000

  main-backend-api:
    container_name: main-backend-api
    build:
      context: ./server/main-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/main-backend:/usr/src/app

    ports:
      - 7070:7070
    env_file:
      - ./server/main-backend/.env
    restart: always
    depends_on:
      - postgres-db
      - redis-db

  file-server:
    build:
      context: ./server/file-server
      dockerfile: dev.Dockerfile
    container_name: file-server

    ports:
      - '5500:5500'
    volumes:
      - ./accounts:/accounts

  postgres-db:
    image: postgres:latest
    container_name: postgres-container-mda
    environment:
      POSTGRES_USER: alx
      POSTGRES_PASSWORD: serbvn
      POSTGRES_DB: mda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    # Redis Cache Service
  redis-db:
    image: redis:latest
    container_name: redis-db
    environment:
      - REDIS_PASSWORD=serbvn
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "serbvn"]

volumes:
  postgres-data:
    driver: local
  accounts-driver:
    driver: local
  redis_data:
    driver: local

