apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web-deployment
  namespace: mda-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-web
  template:
    metadata:
      labels:
        app: client-web
    spec:
      containers:
      - name: client-web
        image: mda-platform/client-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: GITHUB_ID
          valueFrom:
            secretKeyRef:
              name: client-web-secret
              key: github-id
        - name: GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              name: client-web-secret
              key: github-secret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: client-web-secret
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: client-web-secret
              key: google-client-secret
        - name: ACCOUNT_SECRET
          valueFrom:
            secretKeyRef:
              name: client-web-secret
              key: account-secret
        - name: CHANGE_GMAIL_SECRET
          valueFrom:
            secretKeyRef:
              name: client-web-secret
              key: change-gmail-secret
        - name: NEXT_PUBLIC_BACKEND_SERVER
          valueFrom:
            configMapKeyRef:
              name: mda-config
              key: NEXT_PUBLIC_BACKEND_SERVER
        - name: NEXT_PUBLIC_FILE_SERVER
          valueFrom:
            configMapKeyRef:
              name: mda-config
              key: NEXT_PUBLIC_FILE_SERVER
        - name: NEXT_PUBLIC_PROJECTS_SERVER
          valueFrom:
            configMapKeyRef:
              name: mda-config
              key: NEXT_PUBLIC_PROJECTS_SERVER
        - name: NEXT_PUBLIC_TASKS_SERVER
          valueFrom:
            configMapKeyRef:
              name: mda-config
              key: NEXT_PUBLIC_TASKS_SERVER
        - name: NEXT_PUBLIC_DEPLOYMENTS_SERVER
          valueFrom:
            configMapKeyRef:
              name: mda-config
              key: NEXT_PUBLIC_DEPLOYMENTS_SERVER
        - name: NEXT_PUBLIC_MESSAGE_SERVER
          valueFrom:
            configMapKeyRef:
              name: mda-config
              key: NEXT_PUBLIC_MESSAGE_SERVER
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          
apiVersion: v1
kind: Service
metadata:
  name: client-web-service
  namespace: mda-platform
spec:
  selector:
    app: client-web
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP