apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
  namespace: ti-platform
  labels:
    app: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      initContainers: 
      - name: init-directories
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Creating directories in /shared..."
          mkdir -p /shared/accounts
          mkdir -p /shared/projects
          mkdir -p /shared/repos
          mkdir -p /shared/local-deployments
          mkdir -p /shared/messages
          mkdir -p /shared/tmp
          # Set permissions for user 1000 (the app user)
          chown -R 1000:1000 /shared
          chmod -R 755 /shared
          echo "Directories created successfully:"
          ls -la /shared/
          echo "Checking mounted volume:"
          df -h /shared
          echo "Init container completed successfully"
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
        securityContext:
          runAsUser: 0
      containers:
      - name: file-server
        image: s3rbvn/file-server:latest
        ports:
        - containerPort: 5600
        env:
        - name: SERVER_HOST
          value: "0.0.0.0:5600"
        - name: AUTH_USERNAME
          value: "Titan"
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: file-server-secrets
              key: AUTH_PASSWORD
        - name: ACCOUNTS_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: ACCOUNTS_FOLDER_PATH
        - name: PROJECTS_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: PROJECTS_FOLDER_PATH
        - name: REPOSITORIES_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: REPOSITORIES_FOLDER_PATH
        - name: PROJECT_DEPLOYMENT_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: PROJECT_DEPLOYMENT_FOLDER_PATH
        - name: MESSAGES_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: MESSAGES_FOLDER_PATH
        - name: TEMP_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: TEMP_FOLDER_PATH
        - name: SHARED_ROOT_PATH
          valueFrom:
            configMapKeyRef:
              name: ti-config
              key: SHARED_ROOT_PATH
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        readinessProbe:
          httpGet:
            path: /health
            port: 5600
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5600
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-service
  namespace: ti-platform
  labels:
    app: file-server
spec:
  selector:
    app: file-server
  ports:
  - name: http
    port: 5600
    targetPort: 5600
    nodePort: 30560  # Fixed port in valid range
    protocol: TCP
  type: NodePort